- name: confirm whether already installed or not
  register: result
  ignore_errors: True
  shell: ls {{ ansible_env.HOME }}/Library/Fonts |grep Ricty

- name: install fonts
  command: bash -c "cp -f $(brew --cellar ricty)/{{ ricty_version }}/share/fonts/Ricty*.ttf {{ ansible_env.HOME }}/Library/Fonts"
  when: result|failed

- name: clear cache
  command: fc-cache -vf
  when: result|failed
