- name: confirm whether already installed or not
  register: result
  ignore_errors: True
  shell: ls "{{ ansible_user_dir }}"/Library/Fonts |grep Ricty

- name: install fonts
  command: bash -c "cp -f $(brew --prefix ricty)/share/fonts/Ricty*.ttf {{ ansible_user_dir }}/Library/Fonts"
  when: result|failed

- name: clear font cache
  command: fc-cache -vf
  when: result|failed
