---
npm_modules:
  - '@vue/cli'
  - dockerfile-language-server-nodejs
  - docto
  - firebase-tools
  - gapps
  - gh
  - gitmoji-cli
  - htmlhint
  - jsonlint
  - instant-markdown-d
  - mdr
  - neovim
  - ndb
  - node-google-apps-script
  - pretty-diff
  - typescript
  - typescript-language-server
  - vmd
  - vscode-html-languageserver-bin
  - vue-language-server
  - yarn
