- name: confirm whether installed node or not
  register: result
  ignore_errors: True
  shell: node -v |grep "{{ node_version }}"

- name: install node
  shell: fnm use "{{ node_version }}"
  when: result|failed

- name: install npm modules in global
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - eslint
    - gh
    - htmlhint
    - jsctags
    - jsonlint
    - node-google-apps-script
    - npm@5
    - pretty-diff
    - prettier-eslint
    - stylelint
    - tslint
    - webpack
    - yarn
