#
# install brew
#
- name: update brew
  register: result
  ignore_errors: True
  command: >
    brew update

- name: get brew installer
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/brew_install
  when: result is failed

- name: proceed brew installer
  command: >
    ruby /tmp/brew_install
  when: result is failed

#
# install apps
#
- name: tap external homebrew repositories
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_repositories }}"
  when: homebrew_repositories

- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: install Java via Cask for plantuml
  homebrew_cask:
    name: java
    state: present

- name: install and upgrade homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ homebrew_packages }}"
  when: homebrew_packages
