- name: confirm whether installed python or not
  register: result
  ignore_errors: True
  shell: pyenv versions |grep {{ python_version }}

- name: install python
  environment:
    LDFLAGS: "-L/usr/local/opt/zlib/lib"
    CPPFLAGS: "-I/usr/local/opt/zlib/include"
  shell: pyenv install {{ python_version }}
  when: result|failed

- name: set global python version
  shell: pyenv global {{ python_version }}
  when: result|failed

- name: rehash
  shell: pyenv rehash
  when: result|failed

- name: upgrade pip
  shell: pip install --upgrade pip

- name: install pip modules
  pip:
    name={{ item.name | default(item) }}
    state={{ item.state | default('present') }}
  with_items: pip_modules
  when: pip_modules
  sudo: false

- name: re-rehash
  shell: pyenv rehash
  when: result|failed

