---
- name: pyenv init
  ignore_errors: "True"
  shell: pyenv init

- name: confirm whether installed python2 or not
  register: result2
  ignore_errors: "True"
  shell: pyenv versions |grep "{{ python_version2 }}"

- name: install python2
  # environment:
    # PYTHON_CONFIGURE_OPTS: "--enable-shared"
    # LDFLAGS: "-L/usr/local/opt/sqlite/lib -L/usr/local/opt/zlib/lib"
    # CPPFLAGS: "-I/usr/local/opt/sqlite/include -I/usr/local/opt/zlib/include"
    # PYTHON_CONFIGURE_OPTS: "--enable-framework"
    # LDSHARED: "clang -bundle"
    # LDCXXSHARED: "clang++ -bundle"
    # BLDSHARED: "clang -bundle -lpython2.7"
  shell: pyenv install "{{ python_version2 }}"
  when: result2 is failed

- name: use python2
  shell: pyenv global "{{ python_version2 }}"

- name: rehash python2
  shell: pyenv rehash

- name: upgrade pip
  shell: pip install --upgrade pip

- name: install pip modules
  pip:
    name: "{{ pip_modules }}"

- name: confirm whether installed python3 or not
  register: result3
  ignore_errors: "True"
  shell: pyenv versions |grep "{{ python_version3 }}"

- name: install python3
  # environment:
    # PYTHON_CONFIGURE_OPTS: "--enable-shared"
    # LDFLAGS: "-L/usr/local/opt/sqlite/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl/lib"
    # CPPFLAGS: "-I/usr/local/opt/sqlite/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl/include"
    # PKG_CONFIG_PATH: "/usr/local/opt/openssl/lib/pkgconfig"
    # PYTHON_CONFIGURE_OPTS: "--enable-framework"
    # LDSHARED: "clang -bundle"
    # LDCXXSHARED: "clang++ -bundle"
    # BLDSHARED: "clang -bundle -lpython3.6m"
  shell: pyenv install "{{ python_version3 }}"
  when: result3 is failed

- name: use python3
  shell: pyenv global "{{ python_version3 }}"

- name: rehash python3
  shell: pyenv rehash

- name: upgrade pip
  shell: pip install --upgrade pip

- name: install pip3 modules
  pip:
    name: "{{ pip_modules }}"
    executable: pip3
