---
- name: confirm whether installed python2 or not
  register: result2
  ignore_errors: "True"
  shell: pyenv versions |grep "{{ python_version2 }}"

- name: install python2
  environment:
    # PYTHON_CONFIGURE_OPTS: "--enable-shared"
    LDFLAGS: "-L/usr/local/opt/sqlite/lib -L/usr/local/opt/zlib/lib"
    CPPFLAGS: "-I/usr/local/opt/sqlite/include -I/usr/local/opt/zlib/include"
    PYTHON_CONFIGURE_OPTS: "--enable-framework"
    # LDSHARED: "clang -bundle"
    # LDCXXSHARED: "clang++ -bundle"
    # BLDSHARED: "clang -bundle -lpython2.7"
  shell: pyenv install "{{ python_version2 }}"
  when: result2|failed

- name: use python2
  shell: pyenv global "{{ python_version2 }}"
  when: result2|failed

- name: upgrade pip
  shell: pip install --upgrade pip

- name: install pip modules
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pip_modules }}"


- name: confirm whether installed python3 or not
  register: result3
  ignore_errors: "True"
  shell: pyenv versions |grep "{{ python_version3 }}"

- name: install python3
  environment:
    # PYTHON_CONFIGURE_OPTS: "--enable-shared"
    LDFLAGS: "-L/usr/local/opt/sqlite/lib -L/usr/local/opt/zlib/lib"
    CPPFLAGS: "-I/usr/local/opt/sqlite/include -I/usr/local/opt/zlib/include"
    PYTHON_CONFIGURE_OPTS: "--enable-framework"
    # LDSHARED: "clang -bundle"
    # LDCXXSHARED: "clang++ -bundle"
    # BLDSHARED: "clang -bundle -lpython3.6m"
  shell: pyenv install "{{ python_version3 }}"
  when: result3|failed

- name: use python3
  shell: pyenv global "{{ python_version3 }}"
  when: result3|failed

- name: upgrade pip
  shell: pip install --upgrade pip

- name: install pip modules
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pip_modules }}"

- name: install powerline for tmux
  shell: pip install git+git://github.com/Lokaltog/powerline
