---
- name: Copy plist files
  template:
    src: "local.{{ item }}.plist.j2"
    dest: "{{ ansible_user_dir }}/Library/LaunchAgents/local.{{ item }}.plist"
    mode: 0600
  with_items: "{{ plist_files }}"
  when: plist_files

- name: load plist
  shell: "launchctl load {{ ansible_user_dir }}/Library/LaunchAgents/local.{{ item }}.plist && launchctl start local.{{ item }}"
  with_items: "{{ plist_files }}"
  when: plist_files
