- name: change permission for secret key files for SSH
  file: path={{ ansible_env.HOME }}/.ssh/{{ item }} mode=600
  with_items:
    - config
    - game
    - github.dena.jp
    - id_dsa
    - nopass-dsa
