---
- name: About brew
  hosts: localhost
  roles:
    - brew
    - brew-cask
  tasks:
    - name: make repos dir
      file:
        path: "{{ ansible_repos_dir }}"
        state: directory
        mode: "0755"
