---
- name: OSX Local Provisioner
  hosts: localhost
  sudo: no
  vars:
    ricty_version: 3.2.4
    ansible2_version: v2.0.0-0.9.rc4
  #pre_tasks:
  #- stat: path=~/.ssh
  #register: ssh
  roles:
    # App Installations
    #- brew
    #- brew-cask

    # Configurations
    #- dotfiles
    #- zsh
    #- ssh
    - ansible2

