- name: update
  shell: nodebrew selfupdate

- name: confirm whether installed node or not
  register: result
  ignore_errors: True
  shell: nodebrew list |grep {{ node_version }}

- name: mkdir src node
  shell: mkdir -p {{ ansible_env.HOME }}/.nodebrew/src
  when: result|failed

- name: install node
  shell: nodebrew install {{ node_version }}
  when: result|failed

- name: use custom node version
  command: nodebrew use {{ node_version }}
  when: result|failed

- name: install npm modules in global
  npm:
    name={{ item }}
    global=yes
  with_items:
    - jsctags
    - gh
    - eslint
    - gistup
    - pretty-diff

