---
- name: rbenv init
  shell: rbenv init
  ignore_errors: "True"

- name: confirm whether installed ruby or not
  register: result
  ignore_errors: True
  shell: rbenv versions |grep "{{ ruby_version }}"

- name: install ruby
  shell: rbenv install "{{ ruby_version }}"
  when: result is failed

- name: set global ruby version
  shell: rbenv global "{{ ruby_version }}"
  when: result is failed

- name: update gem
  shell: gem update --system; gem update

- name: install gem modules
  gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default('') }}"
    user_install: no
  with_items: "{{ gem_modules }}"
  when: item != ""
