- name: confirm whether installed ruby or not
  register: result
  ignore_errors: True
  shell: rbenv versions |grep {{ ruby_version }}

- name: install ruby
  shell: rbenv install {{ ruby_version }}
  when: result|failed

- name: set global ruby version
  shell: rbenv global {{ ruby_version }}
  when: result|failed

- name: update gem
  shell: gem update --system; gem update

- name: install gem modules
  gem:
    name={{ item.name | default(item) }}
    state={{ item.state | default('present') }}
    version={{ item.version | default('') }}
  with_items: gem_modules
  when: gem_modules
